"""This type stub file was generated by pyright."""

from __future__ import annotations

from docker.transport.ssladapter import SSLHTTPAdapter  # type: ignore[import-not-found]
from docker.transport.unixconn import UnixHTTPAdapter
