"""This type stub file was generated by pyright."""

from __future__ import annotations

import http.client as httplib
import socket

from docker.transport.basehttpadapter import BaseHTTPAdapter

RecentlyUsedContainer = ...

class SSHSocket(socket.socket):
    def __init__(self, host) -> None: ...
    def connect(self, **kwargs): ...  # type: ignore[override]
    def sendall(self, data): ...  # type: ignore[override]
    def send(self, data): ...  # type: ignore[override]
    def recv(self, n): ...  # type: ignore[override]
    def makefile(self, mode): ...  # type: ignore[override]
    def close(self): ...

class SSHConnection(httplib.HTTPConnection):
    def __init__(self, ssh_transport=..., timeout=..., host=...) -> None: ...
    def connect(self): ...

class SSHConnectionPool(urllib3.connectionpool.HTTPConnectionPool):  # type: ignore[name-defined]
    scheme = ...
    def __init__(self, ssh_client=..., timeout=..., maxsize=..., host=...) -> None: ...

class SSHHTTPAdapter(BaseHTTPAdapter):
    __attrs__ = ...  # type: ignore[assignment]
    def __init__(
        self,
        base_url,
        timeout=...,
        pool_connections=...,
        max_pool_size=...,
        shell_out=...,
    ) -> None: ...
    def get_connection(self, url, proxies=...): ...
    def close(self): ...
