"""
This type stub file was generated by pyright.
"""

from . import AWSHelperFn, AWSObject, AWSProperty

EC2_INSTANCE_LAUNCH = "autoscaling:EC2_INSTANCE_LAUNCH"
EC2_INSTANCE_LAUNCH_ERROR = "autoscaling:EC2_INSTANCE_LAUNCH_ERROR"
EC2_INSTANCE_TERMINATE = "autoscaling:EC2_INSTANCE_TERMINATE"
EC2_INSTANCE_TERMINATE_ERROR = "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"
TEST_NOTIFICATION = "autoscaling:TEST_NOTIFICATION"
Default = "Default"
OldestInstance = "OldestInstance"
NewestInstance = "NewestInstance"
OldestLaunchConfiguration = "OldestLaunchConfiguration"
OldestLaunchTemplate = "OldestLaunchTemplate"
ClosestToNextInstanceHour = "ClosestToNextInstanceHour"
AllocationStrategy = "AllocationStrategy"

class Tag(AWSHelperFn):
    def __init__(self, key, value, propogate) -> None: ...

class Tags(AWSHelperFn):
    defaultPropagateAtLaunch = ...
    manyType = ...
    def __init__(self, **kwargs) -> None: ...
    def __add__(self, newtags): ...
    def to_dict(self): ...

class LifecycleHookSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class NotificationConfigurations(AWSProperty):
    props = ...  # type: ignore[assignment]

class MetricsCollection(AWSProperty):
    props = ...  # type: ignore[assignment]

class Metadata(AWSHelperFn):
    def __init__(self, init, authentication=...) -> None: ...
    def validate(self, init, authentication): ...

class LaunchTemplateSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class InstancesDistribution(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateOverrides(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplate(AWSProperty):
    props = ...  # type: ignore[assignment]

class MixedInstancesPolicy(AWSProperty):
    props = ...  # type: ignore[assignment]

class AutoScalingGroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class LaunchConfiguration(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class StepAdjustments(AWSProperty):
    props = ...  # type: ignore[assignment]

class MetricDimension(AWSProperty):
    props = ...  # type: ignore[assignment]

class CustomizedMetricSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class PredefinedMetricSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class TargetTrackingConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class ScalingPolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ScheduledAction(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class LifecycleHook(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Trigger(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class EBSBlockDevice(AWSProperty):
    props = ...  # type: ignore[assignment]

class BlockDeviceMapping(AWSProperty):
    props = ...  # type: ignore[assignment]
