"""This type stub file was generated by pyright."""

from . import AWSObject, AWSProperty

class DomainValidationOption(AWSProperty):
    props = ...  # type: ignore[assignment]

class Certificate(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
