"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

class Cookies(AWSProperty):
    props = ...  # type: ignore[assignment]

class ForwardedValues(AWSProperty):
    props = ...  # type: ignore[assignment]

class LambdaFunctionAssociation(AWSProperty):
    props = ...  # type: ignore[assignment]

class CacheBehavior(AWSProperty):
    props = ...  # type: ignore[assignment]

class DefaultCacheBehavior(AWSProperty):
    props = ...  # type: ignore[assignment]

class S3Origin(AWSProperty):
    props = ...  # type: ignore[assignment]

class CustomOriginConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginCustomHeader(AWSProperty):
    props = ...  # type: ignore[assignment]

class S3OriginConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class Origin(AWSProperty):
    props = ...  # type: ignore[assignment]

class Logging(AWSProperty):
    props = ...  # type: ignore[assignment]

class CustomErrorResponse(AWSProperty):
    props = ...  # type: ignore[assignment]

class GeoRestriction(AWSProperty):
    props = ...  # type: ignore[assignment]

class Restrictions(AWSProperty):
    props = ...  # type: ignore[assignment]

class ViewerCertificate(AWSProperty):
    props = ...  # type: ignore[assignment]

class StatusCodes(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginGroupFailoverCriteria(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginGroupMember(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginGroupMembers(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginGroup(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginGroups(AWSProperty):
    props = ...  # type: ignore[assignment]

class DistributionConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class Distribution(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CloudFrontOriginAccessIdentityConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class CloudFrontOriginAccessIdentity(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TrustedSigners(AWSProperty):
    props = ...  # type: ignore[assignment]

class StreamingDistributionConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class StreamingDistribution(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CacheCookiesConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class CacheHeadersConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class CacheQueryStringsConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ParametersInCacheKeyAndForwardedToOrigin(AWSProperty):
    props = ...  # type: ignore[assignment]

class CachePolicyConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class CachePolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class OriginRequestCookiesConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginRequestHeadersConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginRequestQueryStringsConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginRequestPolicyConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class OriginRequestPolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class KinesisStreamConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class EndPoint(AWSProperty):
    props = ...  # type: ignore[assignment]

class RealtimeLogConfig(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
