"""
This type stub file was generated by pyright.
"""

from . import AWSHelperFn, AWSObject, AWSProperty, BaseAWSObject

class Stack(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class AWSCustomObject(BaseAWSObject):
    dictname = ...  # type: ignore[assignment]

class CustomResource(AWSCustomObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class AutoDeployment(AWSProperty):
    props = ...  # type: ignore[assignment]

class OperationPreferences(AWSProperty):
    props = ...  # type: ignore[assignment]

class Parameter(AWSProperty):
    props = ...  # type: ignore[assignment]

class DeploymentTargets(AWSProperty):
    props = ...  # type: ignore[assignment]

class StackInstances(AWSProperty):
    props = ...  # type: ignore[assignment]

class StackSet(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class WaitCondition(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class WaitConditionHandle(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Metadata(AWSHelperFn):
    def __init__(self, *args) -> None: ...
    def to_dict(self): ...

class InitFileContext(AWSHelperFn):
    def __init__(self, data) -> None: ...

class InitFile(AWSProperty):
    props = ...  # type: ignore[assignment]

class InitFiles(AWSHelperFn):
    def __init__(self, data) -> None: ...
    def validate(self, data): ...

class InitService(AWSProperty):
    props = ...  # type: ignore[assignment]

class InitServices(AWSHelperFn):
    def __init__(self, data) -> None: ...
    def validate(self, data): ...

class InitConfigSets(AWSHelperFn):
    def __init__(self, **kwargs) -> None: ...
    def validate(self, config_sets): ...

class InitConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

def validate_authentication_type(auth_type): ...

class AuthenticationBlock(AWSProperty):
    props = ...  # type: ignore[assignment]

class Authentication(AWSHelperFn):
    def __init__(self, data) -> None: ...
    def validate(self, data): ...

class Init(AWSHelperFn):
    def __init__(self, data, **kwargs) -> None: ...
    def validate(self, data, config_sets): ...

class Macro(AWSCustomObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
