"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

VALID_IMAGE_PULL_CREDENTIALS = ...
VALID_CREDENTIAL_PROVIDERS = ...
VALID_WEBHOOKFILTER_TYPES = ...
VALID_PROJECTFILESYSTEMLOCATION_TYPE = ...

def validate_image_pull_credentials(image_pull_credentials):
    """Validate ImagePullCredentialsType for Project"""
    ...

def validate_credentials_provider(credential_provider):
    """Validate CredentialProvider for Project's RegistryCredential"""
    ...

def validate_webhookfilter_type(webhookfilter_type):
    """Validate WebHookFilter type property for a Project"""
    ...

def validate_projectfilesystemlocation_type(projectfilesystemlocation_type):
    """Validate ProjectFileSystemLocation type property"""
    ...

class SourceAuth(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class Artifacts(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class EnvironmentVariable(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class RegistryCredential(AWSProperty):
    props = ...  # type: ignore[assignment]

class Environment(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class BatchRestrictions(AWSProperty):
    props = ...  # type: ignore[assignment]

class ProjectBuildBatchConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ProjectCache(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class BuildStatusConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class GitSubmodulesConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class Source(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class VpcConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class WebhookFilter(AWSProperty):
    props = ...  # type: ignore[assignment]

class ProjectTriggers(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self):
        """FilterGroups, if set, needs to be a list of a list of
        WebhookFilters
        """
        ...

def validate_status(status):
    """Validate status
    :param status: The Status of CloudWatchLogs or S3Logs
    :return: The provided value if valid
    """
    ...

class CloudWatchLogs(AWSProperty):
    props = ...  # type: ignore[assignment]

class S3Logs(AWSProperty):
    props = ...  # type: ignore[assignment]

class LogsConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ProjectSourceVersion(AWSProperty):
    props = ...  # type: ignore[assignment]

class ProjectFileSystemLocation(AWSProperty):
    props = ...  # type: ignore[assignment]

class Project(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class S3ReportExportConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReportExportConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReportGroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class SourceCredential(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
