"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

VALID_RECOVERYOPTION_NAME = ("admin_only", "verified_email", "verified_phone_number")

def validate_recoveryoption_name(recoveryoption_name):
    """Validate Name for RecoveryOption"""
    ...

class CognitoIdentityProvider(AWSProperty):
    props = ...  # type: ignore[assignment]

class CognitoStreams(AWSProperty):
    props = ...  # type: ignore[assignment]

class PushSync(AWSProperty):
    props = ...  # type: ignore[assignment]

class IdentityPool(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class MappingRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class RulesConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class RoleMapping(AWSProperty):
    props = ...  # type: ignore[assignment]

class IdentityPoolRoleAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class InviteMessageTemplate(AWSProperty):
    props = ...  # type: ignore[assignment]

class AdminCreateUserConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class DeviceConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class EmailConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class LambdaConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class PasswordPolicy(AWSProperty):
    props = ...  # type: ignore[assignment]

class Policies(AWSProperty):
    props = ...  # type: ignore[assignment]

class NumberAttributeConstraints(AWSProperty):
    props = ...  # type: ignore[assignment]

class StringAttributeConstraints(AWSProperty):
    props = ...  # type: ignore[assignment]

class SchemaAttribute(AWSProperty):
    props = ...  # type: ignore[assignment]

class SmsConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolAddOns(AWSProperty):
    props = ...  # type: ignore[assignment]

class VerificationMessageTemplate(AWSProperty):
    props = ...  # type: ignore[assignment]

class RecoveryOption(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccountRecoverySetting(AWSProperty):
    props = ...  # type: ignore[assignment]

class UsernameConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPool(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class AnalyticsConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolClient(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CustomDomainConfigType(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolDomain(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class UserPoolGroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class UserPoolIdentityProvider(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ResourceServerScopeType(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolResourceServer(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class AccountTakeoverActionType(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccountTakeoverActionsType(AWSProperty):
    props = ...  # type: ignore[assignment]

class NotifyEmailType(AWSProperty):
    props = ...  # type: ignore[assignment]

class NotifyConfigurationType(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccountTakeoverRiskConfigurationType(AWSProperty):
    props = ...  # type: ignore[assignment]

class CompromisedCredentialsActionsType(AWSProperty):
    props = ...  # type: ignore[assignment]

class CompromisedCredentialsRiskConfigurationType(AWSProperty):
    props = ...  # type: ignore[assignment]

class RiskExceptionConfigurationType(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolRiskConfigurationAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class UserPoolUICustomizationAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class AttributeType(AWSProperty):
    props = ...  # type: ignore[assignment]

class UserPoolUser(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class UserPoolUserToGroupAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
