"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

def attribute_type_validator(x): ...
def key_type_validator(x): ...
def projection_type_validator(x): ...
def billing_mode_validator(x): ...

class AttributeDefinition(AWSProperty):
    props = ...  # type: ignore[assignment]

class KeySchema(AWSProperty):
    props = ...  # type: ignore[assignment]

class Key(KeySchema):
    """For backwards compatibility."""

    ...

class ProvisionedThroughput(AWSProperty):
    props = ...  # type: ignore[assignment]

class Projection(AWSProperty):
    props = ...  # type: ignore[assignment]

class SSESpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class GlobalSecondaryIndex(AWSProperty):
    props = ...  # type: ignore[assignment]

class LocalSecondaryIndex(AWSProperty):
    props = ...  # type: ignore[assignment]

class PointInTimeRecoverySpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class StreamSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class TimeToLiveSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class Table(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...
