"""
This type stub file was generated by pyright.
"""

from . import AWSHelperFn, AWSObject, AWSProperty

VALID_ELASTICINFERENCEACCELERATOR_TYPES = ("eia1.medium", "eia1.large", "eia1.xlarge")
VALID_CLIENTVPNENDPOINT_VPNPORT = (443, 1194)

def validate_elasticinferenceaccelerator_type(elasticinferenceaccelerator_type):
    """Validate ElasticInferenceAccelerator for Instance"""
    ...

def validate_clientvpnendpoint_vpnport(vpnport):
    """Validate VpnPort for ClientVpnEndpoint"""
    ...

class Tag(AWSProperty):
    props = ...  # type: ignore[assignment]
    def __init__(self, key=..., value=..., **kwargs) -> None: ...

class CarrierGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CustomerGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class DHCPOptions(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class EgressOnlyInternetGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class EIP(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class EIPAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class FlowLog(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class NatGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class EBSBlockDevice(AWSProperty):
    props = ...  # type: ignore[assignment]

NO_DEVICE = {}

class BlockDeviceMapping(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateBlockDeviceMapping(AWSProperty):
    props = ...  # type: ignore[assignment]

class MountPoint(AWSProperty):
    props = ...  # type: ignore[assignment]

class Placement(AWSProperty):
    props = ...  # type: ignore[assignment]

class CpuOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class CreditSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class ElasticGpuSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class Ipv6Addresses(AWSHelperFn):
    def __init__(self, address) -> None: ...

class LaunchTemplateSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class PrivateIpAddressSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class NetworkInterfaceProperty(AWSProperty):
    props = ...  # type: ignore[assignment]

class AssociationParameters(AWSProperty):
    props = ...  # type: ignore[assignment]

class SsmAssociations(AWSProperty):
    props = ...  # type: ignore[assignment]

class GatewayRouteTableAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Host(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ElasticInferenceAccelerator(AWSProperty):
    props = ...  # type: ignore[assignment]

class LicenseSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class HibernationOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class Instance(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class InternetGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class NetworkAcl(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ICMP(AWSProperty):
    props = ...  # type: ignore[assignment]

class PortRange(AWSProperty):
    props = ...  # type: ignore[assignment]

class NetworkAclEntry(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class NetworkInterface(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class NetworkInterfaceAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

PERMISSION_INSTANCE_ATTACH = "INSTANCE-ATTACH"
PERMISSION_EIP_ASSOCIATE = "EIP-ASSOCIATE"

class NetworkInterfacePermission(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Entry(AWSProperty):
    props = ...  # type: ignore[assignment]

class PrefixList(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Route(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class RouteTable(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

def check_ports(props): ...

class SecurityGroupEgress(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class SecurityGroupIngress(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class SecurityGroupRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class SecurityGroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Subnet(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class SubnetNetworkAclAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class SubnetRouteTableAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Volume(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VolumeAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

def instance_tenancy(value): ...

class VPC(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCDHCPOptionsAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCEndpoint(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCEndpointConnectionNotification(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCEndpointService(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCEndpointServicePermissions(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCGatewayAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VpnTunnelOptionsSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class VPNConnection(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class VPNConnectionRoute(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPNGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPNGatewayRoutePropagation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCPeeringConnection(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Monitoring(AWSProperty):
    props = ...  # type: ignore[assignment]

class NetworkInterfaces(AWSProperty):
    props = ...  # type: ignore[assignment]

class SecurityGroups(AWSProperty):
    props = ...  # type: ignore[assignment]

class IamInstanceProfile(AWSProperty):
    props = ...  # type: ignore[assignment]

class SpotFleetTagSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchSpecifications(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateOverrides(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateConfigs(AWSProperty):
    props = ...  # type: ignore[assignment]

class ClassicLoadBalancer(AWSProperty):
    props = ...  # type: ignore[assignment]

class ClassicLoadBalancersConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class TargetGroup(AWSProperty):
    props = ...  # type: ignore[assignment]

class TargetGroupConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class LoadBalancersConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class SpotFleetRequestConfigData(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class SpotFleet(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class PlacementGroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class SubnetCidrBlock(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class VPCCidrBlock(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TagSpecifications(AWSProperty):
    props = ...  # type: ignore[assignment]

class SpotOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class InstanceMarketOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateCreditSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class MetadataOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateElasticInferenceAccelerator(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateData(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplate(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TrafficMirrorFilter(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TrafficMirrorPortRange(AWSProperty):
    props = ...  # type: ignore[assignment]

class TrafficMirrorFilterRule(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TrafficMirrorSession(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TrafficMirrorTarget(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGateway(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGatewayAttachment(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGatewayRoute(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGatewayRouteTable(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGatewayRouteTableAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TransitGatewayRouteTablePropagation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class FleetLaunchTemplateSpecificationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class FleetLaunchTemplateOverridesRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class FleetLaunchTemplateConfigRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class OnDemandOptionsRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class SpotOptionsRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class TargetCapacitySpecificationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class EC2Fleet(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CapacityReservation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ClientVpnAuthorizationRule(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CertificateAuthenticationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class DirectoryServiceAuthenticationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class FederatedAuthenticationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class ClientAuthenticationRequest(AWSProperty):
    props = ...  # type: ignore[assignment]

class ConnectionLogOptions(AWSProperty):
    props = ...  # type: ignore[assignment]

class ClientVpnEndpoint(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ClientVpnRoute(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ClientVpnTargetNetworkAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class LocalGatewayRoute(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class LocalGatewayRouteTableVPCAssociation(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
