"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

class LifecyclePolicy(AWSProperty):
    props = ...  # type: ignore[assignment]

class Repository(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
