"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

class LogSetup(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class Logging(AWSProperty):
    props = ...  # type: ignore[assignment]

class Provider(AWSProperty):
    props = ...  # type: ignore[assignment]

class EncryptionConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class KubernetesNetworkConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class ResourcesVpcConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class Cluster(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Label(AWSProperty):
    props = ...  # type: ignore[assignment]

class Selector(AWSProperty):
    props = ...  # type: ignore[assignment]

class FargateProfile(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class RemoteAccess(AWSProperty):
    props = ...  # type: ignore[assignment]

class ScalingConfig(AWSProperty):
    props = ...  # type: ignore[assignment]

class LaunchTemplateSpecification(AWSProperty):
    props = ...  # type: ignore[assignment]

class Nodegroup(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
