"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

Active = "Active"
Inactive = "Inactive"

class AccessKey(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class PolicyType(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Policy(AWSProperty):
    props = ...  # type: ignore[assignment]

# PolicyProperty = Policy

class Group(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class InstanceProfile(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Role(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ServiceLinkedRole(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class LoginProfile(AWSProperty):
    props = ...  # type: ignore[assignment]

class User(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class UserToGroupAddition(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ManagedPolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
