"""
This type stub file was generated by pyright.
"""

from . import AWSAttribute, AWSProperty

class AutoScalingRollingUpdate(AWSProperty):
    props = ...  # type: ignore[assignment]

class AutoScalingScheduledAction(AWSProperty):
    props = ...  # type: ignore[assignment]

class AutoScalingReplacingUpdate(AWSProperty):
    props = ...  # type: ignore[assignment]

class CodeDeployLambdaAliasUpdate(AWSProperty):
    props = ...  # type: ignore[assignment]

class UpdatePolicy(AWSAttribute):
    props = ...  # type: ignore[assignment]

class ResourceSignal(AWSProperty):
    props = ...  # type: ignore[assignment]

class AutoScalingCreationPolicy(AWSProperty):
    props = ...  # type: ignore[assignment]

class CreationPolicy(AWSAttribute):
    props = ...  # type: ignore[assignment]
