"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

Private = "Private"
PublicRead = "PublicRead"
PublicReadWrite = "PublicReadWrite"
AuthenticatedRead = "AuthenticatedRead"
BucketOwnerRead = "BucketOwnerRead"
BucketOwnerFullControl = "BucketOwnerFullControl"
LogDeliveryWrite = "LogDeliveryWrite"

class PublicAccessBlockConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class VpcConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccessPoint(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class CorsRules(AWSProperty):
    props = ...  # type: ignore[assignment]

class CorsConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class VersioningConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccelerateConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class RedirectAllRequestsTo(AWSProperty):
    props = ...  # type: ignore[assignment]

class RedirectRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class RoutingRuleCondition(AWSProperty):
    props = ...  # type: ignore[assignment]

class RoutingRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class WebsiteConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class LifecycleRuleTransition(AWSProperty):
    props = ...  # type: ignore[assignment]

class AbortIncompleteMultipartUpload(AWSProperty):
    props = ...  # type: ignore[assignment]

class NoncurrentVersionTransition(AWSProperty):
    props = ...  # type: ignore[assignment]

class TagFilter(AWSProperty):
    props = ...  # type: ignore[assignment]

class LifecycleRule(AWSProperty):
    props = ...  # type: ignore[assignment]
    def validate(self): ...

class LifecycleConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class LoggingConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class Rules(AWSProperty):
    props = ...  # type: ignore[assignment]

class S3Key(AWSProperty):
    props = ...  # type: ignore[assignment]

class Filter(AWSProperty):
    props = ...  # type: ignore[assignment]

class LambdaConfigurations(AWSProperty):
    props = ...  # type: ignore[assignment]

class QueueConfigurations(AWSProperty):
    props = ...  # type: ignore[assignment]

class TopicConfigurations(AWSProperty):
    props = ...  # type: ignore[assignment]

class MetricsConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class NotificationConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class OwnershipControlsRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class OwnershipControls(AWSProperty):
    props = ...  # type: ignore[assignment]

class DeleteMarkerReplication(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccessControlTranslation(AWSProperty):
    props = ...  # type: ignore[assignment]

class EncryptionConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationTimeValue(AWSProperty):
    props = ...  # type: ignore[assignment]

class Metrics(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationTime(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationConfigurationRulesDestination(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationRuleAndOperator(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationRuleFilter(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicaModifications(AWSProperty):
    props = ...  # type: ignore[assignment]

class SseKmsEncryptedObjects(AWSProperty):
    props = ...  # type: ignore[assignment]

class SourceSelectionCriteria(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationConfigurationRules(AWSProperty):
    props = ...  # type: ignore[assignment]

class ReplicationConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class Destination(AWSProperty):
    props = ...  # type: ignore[assignment]

class DataExport(AWSProperty):
    props = ...  # type: ignore[assignment]

class StorageClassAnalysis(AWSProperty):
    props = ...  # type: ignore[assignment]

class AnalyticsConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class ServerSideEncryptionByDefault(AWSProperty):
    props = ...  # type: ignore[assignment]

class ServerSideEncryptionRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class BucketEncryption(AWSProperty):
    props = ...  # type: ignore[assignment]

class InventoryConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class DefaultRetention(AWSProperty):
    props = ...  # type: ignore[assignment]

class ObjectLockRule(AWSProperty):
    props = ...  # type: ignore[assignment]

class ObjectLockConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class Bucket(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
    access_control_types = ...
    def validate(self): ...

class BucketPolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class ActivityMetrics(AWSProperty):
    props = ...  # type: ignore[assignment]

class SelectionCriteria(AWSProperty):
    props = ...  # type: ignore[assignment]

class PrefixLevelStorageMetrics(AWSProperty):
    props = ...  # type: ignore[assignment]

class PrefixLevel(AWSProperty):
    props = ...  # type: ignore[assignment]

class BucketLevel(AWSProperty):
    props = ...  # type: ignore[assignment]

class AccountLevel(AWSProperty):
    props = ...  # type: ignore[assignment]

class AwsOrg(AWSProperty):
    props = ...  # type: ignore[assignment]

class BucketsAndRegions(AWSProperty):
    props = ...  # type: ignore[assignment]

class StorageLensConfiguration(AWSProperty):
    props = ...  # type: ignore[assignment]

class StorageLens(AWSObject):
    resource_type: str = ...

    props = ...  # type: ignore[assignment]
