"""
This type stub file was generated by pyright.
"""

from . import AWSObject, AWSProperty

class Subscription(AWSProperty):
    props = ...  # type: ignore[assignment]

class SubscriptionResource(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class TopicPolicy(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]

class Topic(AWSObject):
    resource_type = ...
    props = ...  # type: ignore[assignment]
