# @config-manager:start python-top-level
'python.analysis.autoFormatStrings' = true
'python.analysis.autoImportCompletions' = true
'python.analysis.completeFunctionParens' = true
'python.analysis.inlayHints.functionReturnTypes' = true
'python.analysis.inlayHints.pytestParameters' = true
'python.analysis.inlayHints.variableTypes' = true
'python.analysis.typeCheckingMode' = 'strict'
'python.analysis.typeEvaluation.deprecateTypingAliases' = true
'python.defaultInterpreterPath' = 'python3'
'python.languageServer' = 'Pylance'
'python.missingPackage.severity' = 'Information'
'python.terminal.activateEnvInCurrentTerminal' = true
'pythonTestExplorer.testFramework' = 'pytest'
'yapf.args' = [ '-i', '*.py' ]
# @config-manager:end python-top-level

# @config-manager:start python
['[python]']
  'editor.formatOnType' = true
  # @config-manager:end python
