---
name: Spell Check

# There is an official action published by cSpell.
# v1.1.1 was tested but did not function as desired so we are using the CLI.

on:
  pull_request: # any pull request
  push:
    branches:
      - master
      - release/v*

env:
  NODE_VERSION: '20'

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: 🏗 Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION }}
      - name: ⤵️ Install Node Dependencies
        run: make setup-npm
      - name: 🚀 Run spellcheck
        run: make spellcheck
